### ISSUE TITLE
where is the file deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7?

### ISSUE THREAD

**Issue by thanhchinh** [noorkhokhar99/YOLOv8-Object-Detection-with-DeepSORT-Tracking#1]
8\YOLOv8-Object-Detection-with-DeepSORT-Tracking\yolo\v8\detect>python tracking_vehicle_counting.py model=yolov8l.pt source="1.mp4"
Error executing job with overrides: ['model=yolov8l.pt', 'source=1.mp4']
Traceback (most recent call last):
  File "C:\yolov8\YOLOv8-Object-Detection-with-DeepSORT-Tracking\yolo\v8\detect\tracking_vehicle_counting.py", line 310, in predict
    init_tracker()
  File "C:\yolov8\YOLOv8-Object-Detection-with-DeepSORT-Tracking\yolo\v8\detect\tracking_vehicle_counting.py", line 38, in init_tracker
    deepsort= DeepSort(cfg_deep.DEEPSORT.REID_CKPT,
  File "C:\yolov8\YOLOv8-Object-Detection-with-DeepSORT-Tracking\yolo\v8\detect\deep_sort_pytorch\deep_sort\deep_sort.py", line 18, in __init__
    self.extractor = Extractor(model_path, use_cuda=use_cuda)
  File "C:\yolov8\YOLOv8-Object-Detection-with-DeepSORT-Tracking\yolo\v8\detect\deep_sort_pytorch\deep_sort\deep\feature_extractor.py", line 14, in __init__
    state_dict = torch.load(model_path, map_location=torch.device(self.device))[
  File "C:\Users\CHINH.TRUONGTHANH\.conda\envs\yolov8\lib\site-packages\torch\serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\CHINH.TRUONGTHANH\.conda\envs\yolov8\lib\site-packages\torch\serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\CHINH.TRUONGTHANH\.conda\envs\yolov8\lib\site-packages\torch\serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by APJayChan** [comment]
here -> https://drive.google.com/file/d/1U8e7JcWDQyLrlpiCkcnh1gkmebaGO8vh/view?usp=share_link

**Comment by HungNgoCT** [comment]
> 8\YOLOv8-Object-Detection-with-DeepSORT-Tracking\yolo\v8\detect>python tracking_vehicle_counting.py model=yolov8l.pt source="1.mp4" Error executing job with overrides: ['model=yolov8l.pt', 'source=1.mp4'] Traceback (most recent call last): File "C:\yolov8\YOLOv8-Object-Detection-with-DeepSORT-Tracking\yolo\v8\detect\tracking_vehicle_counting.py", line 310, in predict init_tracker() File "C:\yolov8\YOLOv8-Object-Detection-with-DeepSORT-Tracking\yolo\v8\detect\tracking_vehicle_counting.py", line 38, in init_tracker deepsort= DeepSort(cfg_deep.DEEPSORT.REID_CKPT, File "C:\yolov8\YOLOv8-Object-Detection-with-DeepSORT-Tracking\yolo\v8\detect\deep_sort_pytorch\deep_sort\deep_sort.py", line 18, in **init** self.extractor = Extractor(model_path, use_cuda=use_cuda) File "C:\yolov8\YOLOv8-Object-Detection-with-DeepSORT-Tracking\yolo\v8\detect\deep_sort_pytorch\deep_sort\deep\feature_extractor.py", line 14, in **init** state_dict = torch.load(model_path, map_location=torch.device(self.device))[ File "C:\Users\CHINH.TRUONGTHANH.conda\envs\yolov8\lib\site-packages\torch\serialization.py", line 699, in load with _open_file_like(f, 'rb') as opened_file: File "C:\Users\CHINH.TRUONGTHANH.conda\envs\yolov8\lib\site-packages\torch\serialization.py", line 231, in _open_file_like return _open_file(name_or_buffer, mode) File "C:\Users\CHINH.TRUONGTHANH.conda\envs\yolov8\lib\site-packages\torch\serialization.py", line 212, in **init** super(_open_file, self).**init**(open(name, mode)) FileNotFoundError: [Errno 2] No such file or directory: 'deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7'
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
The same problem.

@APJayChan  How to correct this problem?
